-- Run this entire script in Supabase: Dashboard → SQL Editor → New query → Run.
-- Fixes: "Could not find the table 'public.live_feed_entries' in the schema cache"
-- (1) Creates the table if it was never created, and (2) tells the API layer to reload.

create extension if not exists "pgcrypto";

create table if not exists public.live_feed_entries (
  id uuid primary key default gen_random_uuid(),
  feed_number bigint generated by default as identity,
  body text not null default '',
  image_url text,
  created_at timestamptz not null default now(),
  constraint live_feed_entries_content_chk check (
    char_length(trim(body)) > 0
    or (
      image_url is not null
      and char_length(trim(image_url)) > 0
    )
  )
);

create index if not exists live_feed_entries_created_idx
  on public.live_feed_entries (created_at desc);

alter table public.live_feed_entries enable row level security;

drop policy if exists "live_feed_select_public" on public.live_feed_entries;
create policy "live_feed_select_public" on public.live_feed_entries
  for select using (true);

-- Refresh PostgREST so REST/JS client sees the new table immediately
notify pgrst, 'reload schema';
