-- Run in Supabase SQL Editor (Database → SQL).
-- Adjust storage policies if your project already has bucket RLS templates.

create extension if not exists "pgcrypto";

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  blurb text,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts (id) on delete cascade,
  order_index int not null,
  kind text not null check (kind in ('text', 'image')),
  sender text not null,
  time_label text not null,
  body text,
  image_url text,
  image_caption text
);

create index if not exists messages_post_order_idx on public.messages (post_id, order_index);

alter table public.posts enable row level security;
alter table public.messages enable row level security;

drop policy if exists "posts_select_public" on public.posts;
create policy "posts_select_public" on public.posts for select using (true);

drop policy if exists "messages_select_public" on public.messages;
create policy "messages_select_public" on public.messages for select using (true);

insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "blog_images_public_read" on storage.objects;
create policy "blog_images_public_read"
on storage.objects for select
to public
using (bucket_id = 'blog-images');

-- Live micro-feed (single-line updates, chronological stream; optional image)
create table if not exists public.live_feed_entries (
  id uuid primary key default gen_random_uuid(),
  feed_number bigint generated by default as identity,
  body text not null default '',
  image_url text,
  created_at timestamptz not null default now(),
  constraint live_feed_entries_content_chk check (
    char_length(trim(body)) > 0
    or (
      image_url is not null
      and char_length(trim(image_url)) > 0
    )
  )
);

create index if not exists live_feed_entries_created_idx
  on public.live_feed_entries (created_at desc);

alter table public.live_feed_entries enable row level security;

drop policy if exists "live_feed_select_public" on public.live_feed_entries;
create policy "live_feed_select_public" on public.live_feed_entries
  for select using (true);

-- Digital pin board (free-positioned images and styled text)
create table if not exists public.board_items (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('image', 'text')),
  image_url text,
  text text,
  x numeric not null default 10,
  y numeric not null default 10,
  width numeric not null default 220,
  height numeric,
  rotation numeric not null default 0,
  z_index int not null default 1,
  font_family text,
  font_size numeric,
  color text,
  is_bold boolean not null default false,
  is_italic boolean not null default false,
  is_underline boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint board_items_content_chk check (
    (kind = 'image' and image_url is not null and char_length(trim(image_url)) > 0)
    or
    (kind = 'text' and text is not null and char_length(trim(text)) > 0)
  )
);

alter table public.board_items
  add column if not exists is_bold boolean not null default false,
  add column if not exists is_italic boolean not null default false,
  add column if not exists is_underline boolean not null default false;

create index if not exists board_items_z_idx
  on public.board_items (z_index asc, created_at asc);

alter table public.board_items enable row level security;

drop policy if exists "board_items_select_public" on public.board_items;
create policy "board_items_select_public" on public.board_items
  for select using (true);

-- So the Supabase API sees new tables without waiting on cache refresh
notify pgrst, 'reload schema';
